name: detect-changes-dispatcher
on:
  push:
    branches:
      - 'master'

jobs:
  dispatch-command:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          commands: detect-changes
